version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "AAABBBCCC"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
